use tpch;

DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS lineitem;
DROP TABLE IF EXISTS nation;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS partsupp;
DROP TABLE IF EXISTS part;
DROP TABLE IF EXISTS region;
DROP TABLE IF EXISTS supplier;


CREATE TABLE customer STORED AS PARQUET AS SELECT * FROM customer_temp;
CREATE TABLE lineitem STORED AS PARQUET AS SELECT * FROM lineitem_temp;
CREATE TABLE nation STORED AS PARQUET AS SELECT * FROM nation_temp;
CREATE TABLE orders STORED AS PARQUET AS SELECT * FROM orders_temp;
CREATE TABLE partsupp STORED AS PARQUET AS SELECT * FROM partsupp_temp;
CREATE TABLE part STORED AS PARQUET AS SELECT * FROM part_temp;
CREATE TABLE region STORED AS PARQUET AS SELECT * FROM region_temp;
CREATE TABLE supplier STORED AS PARQUET AS SELECT * FROM supplier_temp;
